name: ci

on:
  push:
    branches:
      - "*" # run for branches
    tags:
      - "*" # run for tags
  pull_request:
    branches:
      - "*" # run for branches
    tags:
      - "*" # run for tags

env:
  GROUP: weaveworksdemos
  COMMIT_SHA: ${{ github.sha }}
  REPO: front-end

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "4.x"

      - run: npm install

      - name: Test image
        env:
          DOCKER_BUILDKIT: 1
        run: make test

  docker:
    needs:
      - test
    runs-on: ubuntu-latest
    env:
      PUSH_DOCKER_IMAGE: true
      DOCKER_NAME: ghcr.io/${{ github.repository }}
      DOCKER_REGISTRY: ghcr.io
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        uses: docker/build-push-action@v1
        with:
          push: false
          repository: ${{ env.GROUP }}/${{ env.REPO }}
          tag_with_ref: true
          tag_with_sha: true
          tags: ${{ github.sha }}

      # - name: Test docker image
      #   env:
      #     DOCKER_BUILDKIT: 1
      #   run: ./test/container.sh

      - name: Login to GHCR
        uses: docker/login-action@v1
        if: env.PUSH_DOCKER_IMAGE == 'true'
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.DOCKER_REGISTRY }}

      - name: Push to ghcr.io
        uses: docker/build-push-action@v2
        if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
        with:
          tags: ${{ env.DOCKER_NAME }}:${{ env.COMMIT_SHA }}
          push: ${{ env.PUSH_DOCKER_IMAGE }}
      # - name: Push to Docker Hub
      #   uses: docker/build-push-action@v1
      #   if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
      #   with:
      #     username: ${{ secrets.DOCKER_USER }}
      #     password: ${{ secrets.DOCKER_PASS }}
      #     repository: ${{ env.GROUP }}/${{ env.REPO }}
      #     tag_with_ref: true
      #     tag_with_sha: true
